name: Go CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run

      - name: Run unit tests
        run: |
          go test ./...

      - name: Build Go application
        run: go build -o app main.go

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to staging server
        run: scp -r app user@staging-server:/path/to/deployment/location

      - name: Restart Go application on staging server
        run: ssh user@staging-server "systemctl restart go-app"
